version: '3'

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  lint:
    desc: Run ruff linter
    cmds:
      - echo "Running ruff linter..."
      - pixi run ruff check .

  format:
    desc: Format code with ruff
    cmds:
      - echo "Formatting code..."
      - pixi run ruff format .

  fix:
    desc: Fix the code with ruff
    cmds:
      - echo "Fixing code ..."
      - pixi run ruff check . --fix
      
  test:
    desc: Run pytest
    cmds:
      - echo "Running tests..."
      - pixi run pytest {{.CLI_ARGS}}
    
  test:cov:
    desc: Run pytest with coverage
    cmds:
      - echo "Running tests with coverage..."
      - pixi run pytest --cov=. tests/
      - pixi run coverage html